on: [pull_request]

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: "Test Action Job"
    steps:
      - uses: actions/checkout@v1
      - name: "Test Action"
        uses: influxdata/clasee@v1
        with:
          spreadsheet: "1Pnv4Xv7n08tD8frCKhqprj5QxEszy4MtNJInIMS9jgs"
        env:
          clasee_secret: ${{ secrets.CLASEE_SECRET }}
